RecipeWeb/Models/Recipe.cs
using System;
using Microsoft.AspNetCore.Identity;
using System.ComponentModel.DataAnnotations;
using System.Xml;
using System.Collections;
using System.Data;
using System.Data.OleDb;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Http;

namespace RecipeWeb.Models
{
    public class Recipe
    {
        [Key]
        public int Id { get; set; }
        public IdentityUser Author { get; set; }

        public string Name { get; set; }

        [Required]
        public string Description { get; set; }

        [Required]
        public string Ingredients { get; set; }

        [Required]
        public string Directions { get; set; }

        [Required]
        public string Picture { get; set; }

        [NotMapped]
        public IFormFile ImageFile { get; set; }

        public virtual ICollection<Comment> Comments { get; set; }

        [Required]
        [ForeignKey("CategoryId")]
        public int CategoryId { get; set; }
        public Category Category { get; set; }

    }
}

RecipeWeb/Models/category.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace RecipeWeb.Models
{
    public class Category
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string Code { get; set; }

        [Required]
        public string Name { get; set; }

        public virtual ICollection<Recipe> Recipes { get; set; }
    }
}

RecipeWeb/Pages/Admin/Category.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Identity;
using System.ComponentModel.DataAnnotations;
using Microsoft.EntityFrameworkCore;
using RecipeWeb.Data;
using RecipeWeb.Models;

namespace RecipeWeb.Pages.Admin
{
    public class CategoryModel : PageModel
    {
        private readonly ApplicationDbContext db;
        public CategoryModel(ApplicationDbContext db) => this.db = db;
        public List<Category> Categories { get; set; }
        [BindProperty]
        public string Name { get; set; }
        [BindProperty]
        [Required]
        public string Code { get; set; }
        [Required]
        public Category category { get; set; }

        public async Task OnGetAsync()
        {
            Categories = await db.Categories.ToListAsync();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                var newCategory = new Category { Code = Code, Name = Name };
                db.Add(newCategory);
                await db.SaveChangesAsync();
                return Page();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostDeleteAsync(int Id)
        {

            category = await db.Categories.FindAsync(Id);
            if (category != null)
            {
                db.Categories.Remove(category);
                await db.SaveChangesAsync();
                return RedirectToPage("/admin/category");
            }
            return Page();
        }

        public async Task<IActionResult> OnPostCreateAsync()
        {
            if (ModelState.IsValid)
            {
                var newCategory = new Category { Code = Code, Name = Name };
                db.Add(newCategory);
                await db.SaveChangesAsync();
                return RedirectToPage("/admin/category");
            }
            return RedirectToPage("/admin/category");
        }

    }
}

RecipeWeb/Pages/Admin/Recipe.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using RecipeWeb.Data;
using RecipeWeb.Models;

namespace RecipeWeb.Pages.Admin
{
    public class RecipeModel : PageModel
    {
        private readonly ApplicationDbContext db;
        public RecipeModel(ApplicationDbContext db) => this.db = db;
        public List<Recipe> Recipes { get; set; }
        public Recipe recipe { get; set; }
        public async Task OnGetAsync()
        {
            Recipes = await db.Recipes.ToListAsync();
        }

        public async Task<IActionResult> OnPostDeleteAsync(int Id)
        {
            recipe = await db.Recipes.FindAsync(Id);
            if (recipe != null)
            {
                db.Recipes.Remove(recipe);
                await db.SaveChangesAsync();
                return RedirectToPage("/Admin/recipe");

            }
            return RedirectToPage("/Admin/recipe");
        }
    }
}

RecipeWeb/Pages/Admin/User.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Identity;

using Microsoft.EntityFrameworkCore;
using RecipeWeb.Data;
using RecipeWeb.Models;

namespace RecipeWeb.Pages.Admin
{
    public class UserModel : PageModel
    {
        //     private readonly ApplicationDbContext db;
        //     public UserModel(ApplicationDbContext db) => this.db = db;

        public IdentityUser IdeUser { get; set; }
        public string Role { get; set; }
        public IList<string> RoleNames { get; set; }
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        public UserModel(UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }

        public List<IdentityUser> UserList { get; set; }
        public async Task OnGetAsync()
        {
            UserList = await _userManager.Users.ToListAsync();
        }
        public async Task<IActionResult> OnPostDeleteAsync(string Id)
        {
            if (Id == null)
            {
                return NotFound();
            }
            IdeUser = await _userManager.FindByIdAsync(Id);
            if (IdeUser != null)
            {
                await _userManager.DeleteAsync(IdeUser);

            }
            return RedirectToPage("/Admin/user");
        }

        public async Task<IActionResult> OnPostEditAsync(string UserName, string Role)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            IdeUser = await _userManager.FindByNameAsync(UserName);
            if (IdeUser != null)
            {
                RoleNames = await _userManager.GetRolesAsync(IdeUser);
                await _userManager.RemoveFromRolesAsync(IdeUser, RoleNames);
                await _userManager.AddToRoleAsync(IdeUser, Role);
            }

            IdentityResult result = await _userManager.UpdateAsync(IdeUser);
            if (!result.Succeeded)
            {
                return Page();
            }
            return RedirectToPage("/Admin/user");

        }
    }
}

RecipeWeb/Pages/Recipe.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using RecipeWeb.Data;
using RecipeWeb.Models;

namespace RecipeWeb.Pages
{
    public class RecipeModel : PageModel
    {
        private readonly ApplicationDbContext db;
        public RecipeModel(ApplicationDbContext db) => this.db = db;
        [BindProperty(SupportsGet = true)]
        public int Id { get; set; }
        public Recipe Recipe { get; set; }
        public int AveRating { get; set; }
        public int UserId { get; }
        public IList<Comment> commentList { get; set; }
        public async Task<IActionResult> OnGetAsync()
        {
            Recipe = await db.Recipes.FindAsync(Id);
            commentList = db.Comments.Where(r => r.RecipeId == Id).ToList();
            if(commentList.Any()){
            AveRating = Convert.ToInt16(Math.Round(commentList.Average(cl => cl.Rating), 0));
            }
            return Page();
        }
        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                var userName = User.Identity.Name;
                var user = db.Users.Where(u => u.UserName == userName).FirstOrDefault();
                var commentBody = Request.Form["commentBody"];
                var rating = Convert.ToInt16(Request.Form["rating"]);
                var newComment = new Comment { Author = user, RecipeId = Id, Rating = rating, CommentBody = commentBody };
                db.Add(newComment);
                await db.SaveChangesAsync();
                return RedirectToPage("Recipe",Id);
            }
            return Page();
        }

    }
}

RecipeWeb/Pages/Admin/Category.cshtml
@page
@model RecipeWeb.Pages.Admin.CategoryModel
@{
ViewData["Title"] = "Admin-Recipe";
Layout = "_AdminLayout";
}


<div class="card-body col-md-9">
    <table id="categorytable" class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Id</th>
                <th>Code</th>
                <th>Name</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var Category in Model.Categories)
            {
            <tr>
                <td>@Category.Id</td>
                <td>@Category.Code</td>
                <td>@Category.Name</td>
                <td>
                    <button id="btndelCategory" form="delform" type="submit" class="btn btn-primary btn-default">
                        Delete
                    </button>
                    <form id="delform" role="form" asp-page-handler="delete" asp-route-id="@Category.Id" method="post"
                        display="none">
                    </form>
                </td>
            </tr>
            }
        <tfoot>
            <tr>
                <form asp-page-handler="create">
                    <th></th>
                    <th>
                        <input asp-for="Code" class="form-control" />
                        <span asp-validation-for="Code" class="text-danger"></span>
                    </th>
                    <th>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </th>
                    <th>
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </th>
                </form>
            </tr>
        </tfoot>
    </table>
</div>
<!-- /.card-body -->


@section Scripts {
<script type="text/javascript">
    $(document).ready(function () {
        var element = document.getElementById('navcategory');
        element.classList.add('active');
    });
</script>
}

RecipeWeb/Pages/Admin/Recipe.cshtml
@page
@model RecipeWeb.Pages.Admin.RecipeModel
@{
ViewData["Title"] = "Admin-Recipe";
Layout = "_AdminLayout";
}

<div class="card-body col-md-9">
  <table id="recipetable" class="table table-bordered table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Picture</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      @foreach (var Recipe in Model.Recipes)
      {
      <tr>
        <td>@Recipe.Name</td>
        <td>@Recipe.Description</td>
        <td><img class="Recipe-image img-fluid img-thumbnail" src="~/Images/@Recipe.Picture" alt="Image of @Recipe.Name"
            width="150" /></td>
        <td>
          <button id="btndelRecipe" form="delform" type="submit" class="btn btn-primary btn-default">
            Delete
          </button>
          <form id="delform" role="form" asp-page-handler="delete" asp-route-id="@Recipe.Id" method="post" display="none">
          </form>
        </td>
      </tr>
      }

      </tfoot>
  </table>
</div>
<!-- /.card-body -->

@section Scripts {
<script type="text/javascript">
  $(document).ready(function () {
    var element = document.getElementById('navrecipe');
    element.classList.add('active');
  });
</script>
}

RecipeWeb/Pages/Admin/User.cshtml
@page
@model RecipeWeb.Pages.Admin.UserModel
@{
ViewData["Title"] = "Admin-User";
Layout = "_AdminLayout";
}

<div class="card-body col-md-9">
  <table id="usertable" class="table table-bordered table-striped">
    <thead>
      <tr>

        <th width="30%">User Email</th>
        @* <th>Role</th> *@
        <th colspan="3">Action</th>
      </tr>
    </thead>
    <tbody>
      @foreach (var user in Model.UserList)
      {
      <tr>
        <td>@user.Email</td>
        @* <td></td> *@
        <td>
          <button id="btnsetAdmin" form="setform @user.Email" type="submit" class="btn btn-primary btn-default">
            Set Admin
          </button>
          <form id="setform @user.Email" role="form" asp-page-handler="edit" asp-route-UserName="@user.Email"
            asp-route-Role="Admin" method="post" display="none">
          </form>
        </td>
        <td>
          <button id="btnrevokeAdmin" form="revokeform @user.Email" type="submit" class="btn btn-primary btn-default">
            Revoke Admin
          </button>
          <form id="revokeform @user.Email" role="form" asp-page-handler="edit" asp-route-UserName="@user.Email"
            asp-route-Role="User" method="post" display="none">
          </form>
        </td>
        <td>
          <button id="btndelUser" form="delform" type="submit" class="btn btn-primary btn-default">
            Delete User
          </button>
          <form id="delform" role="form" asp-page-handler="delete" asp-route-id="@user.Id" method="post" display="none">
          </form>
        </td>
      </tr>
      }

      </tfoot>
  </table>
</div>
<!-- /.card-body -->

@section Scripts {
<script type="text/javascript">
  $(document).ready(function () {
    var element = document.getElementById('navuser');
    element.classList.add('active');
  });
</script>
}